server:
  error:
    include-message: always
    include-binding-errors: always
  port: 9090

spring:
  main:
    allow-circular-references: true
  datasource:
      password: boniface
      url: jdbc:mysql://localhost:3306/martin?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
      username: boniface

  hikari:
    poolName: Hikari
    auto-commit: false



  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

  properties:
    mail:
      smtp:
        ssl:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 300000
        timeout: 3000
        writetimeout: 5000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
