server:
  error:
    include-message: always
    include-binding-errors: always
  port: 9090

spring:
  datasource:
  #    password: '@Joaninah1'
  #    url: jdbc:mysql://localhost:3306/cheri?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
  #    username: joaninah
  #password: natujenge
  #url: jdbc:mysql://51.15.141.206:3308/cheri?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
  #username: natujenge
      password: 'password123A$'
      url: jdbc:mysql://localhost:3306/martin?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
      username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

  properties:
    mail:
      smtp:
        ssl:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 300000
        timeout: 3000
        writetimeout: 5000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
